package app

import (
	"orchestrator/internal/activities"
	"orchestrator/internal/workflows"

	workflowruntime "github.com/byte-v-forge/workflow-runtime"
)

func temporalWorkerSpec(taskQueue string, s *activities.Server) workflowruntime.WorkerSpec {
	return workflowruntime.WorkerSpec{
		TaskQueue: taskQueue,
		Workflows: []workflowruntime.WorkflowDefinition{
			{Name: "RegisterAccountWorkflow", Definition: workflows.RegisterAccountWorkflow},
			{Name: "ActivateAccountWorkflow", Definition: workflows.ActivateAccountWorkflow},
			{Name: "AutoPayWorkflow", Definition: workflows.AutoPayWorkflow},
			{Name: "GoPayAppWorkflow", Definition: workflows.GoPayAppWorkflow},
			{Name: "GoPayAppAuthWorkflow", Definition: workflows.GoPayAppAuthWorkflow},
			{Name: "GoPayAppEnsureTokenWorkflow", Definition: workflows.GoPayAppEnsureTokenWorkflow},
			{Name: "GoPayAppChangePhoneWorkflow", Definition: workflows.GoPayAppChangePhoneWorkflow},
			{Name: "GoPayAppDeactivateWorkflow", Definition: workflows.GoPayAppDeactivateWorkflow},
			{Name: "GoPayAppSignupWorkflow", Definition: workflows.GoPayAppSignupWorkflow},
			{Name: "GoPayAppCreatePinWorkflow", Definition: workflows.GoPayAppCreatePinWorkflow},
			{Name: "GoPayPaymentWorkflow", Definition: workflows.GoPayPaymentWorkflow},
			{Name: "GoPayWAPaymentWorkflow", Definition: workflows.GoPayWAPaymentWorkflow},
			{Name: "GoPayPaymentRebindWorkflow", Definition: workflows.GoPayPaymentRebindWorkflow},
			{Name: "ProbeAccountWorkflow", Definition: workflows.ProbeAccountWorkflow},
			{Name: "LoginSessionWorkflow", Definition: workflows.LoginSessionWorkflow},
			{Name: "RegisterAndActivateWorkflow", Definition: workflows.RegisterAndActivateWorkflow},
		},
		Activities: []workflowruntime.ActivityDefinition{
			{Name: createJobActivityName, Definition: s.CreateJobActivity},
			{Name: startJobStepActivityName, Definition: s.StartJobStepActivity},
			{Name: completeJobStepActivityName, Definition: s.CompleteJobStepActivity},
			{Name: ensureAccountActivityName, Definition: s.EnsureAccountActivity},
			{Name: resolveAccountActivityName, Definition: s.ResolveAccountFromJobActivity},
			{Name: browserAuthStartActivityName, Definition: s.BrowserAuthStartActivity},
			{Name: browserAuthWaitActivityName, Definition: s.BrowserAuthWaitActivity},
			{Name: browserAuthResendOTPActivityName, Definition: s.BrowserAuthResendOTPActivity},
			{Name: browserAuthCompleteActivityName, Definition: s.BrowserAuthCompleteActivity},
			{Name: browserAuthCancelActivityName, Definition: s.BrowserAuthCancelActivity},
			{Name: waitOTPActivityName, Definition: s.OTPWaitActivity},
			{Name: fetchManualOTPActivityName, Definition: s.FetchManualOTPActivity},
			{Name: ensureLogonActivityName, Definition: s.EnsureLogonActivity},
			{Name: goPayPaymentPrepareActivityName, Definition: s.GoPayPaymentPrepareActivity},
			{Name: goPayPaymentStartActivityName, Definition: s.GoPayPaymentStartActivity},
			{Name: goPayPaymentOTPResendActivityName, Definition: s.GoPayPaymentOTPResendActivity},
			{Name: goPayPaymentCompleteActivityName, Definition: s.GoPayPaymentCompleteActivity},
			{Name: goPayPaymentCancelActivityName, Definition: s.GoPayPaymentCancelActivity},
			{Name: goPayResolveWAPhoneActivityName, Definition: s.GoPayResolveWAPhoneActivity},
			{Name: goPayAppLoadStateActivityName, Definition: s.GoPayAppLoadStateActivity},
			{Name: goPayAppSaveStateActivityName, Definition: s.GoPayAppSaveStateActivity},
			{Name: goPayAppDeleteStateActivityName, Definition: s.GoPayAppDeleteStateActivity},
			{Name: goPayPaymentRebindSourceActivityName, Definition: s.GoPayPaymentRebindSourceActivity},
			{Name: goPayAppOTPStartActivityName, Definition: s.GoPayAppOTPStartActivity},
			{Name: goPayAppOTPCompleteActivityName, Definition: s.GoPayAppOTPCompleteActivity},
			{Name: goPayAppOTPRetryActivityName, Definition: s.GoPayAppOTPRetryActivity},
			{Name: goPayAppStatusActivityName, Definition: s.GoPayAppStatusActivity},
			{Name: goPayAppCreatePinStartActivityName, Definition: s.GoPayAppCreatePinStartActivity},
			{Name: goPayAppCreatePinRetryActivityName, Definition: s.GoPayAppCreatePinRetryActivity},
			{Name: goPayAppCreatePinCompleteActivityName, Definition: s.GoPayAppCreatePinCompleteActivity},
			{Name: goPayAppAcquireSignupPhoneActivityName, Definition: s.GoPayAppAcquireSignupPhoneActivity},
			{Name: goPayAppDiscardSignupPhoneActivityName, Definition: s.GoPayAppDiscardSignupPhoneActivity},
			{Name: goPayAppAddBalanceActivityName, Definition: s.GoPayAppAddBalanceActivity},
			{Name: goPayAppChangePhoneGetNumberActivityName, Definition: s.GoPayAppChangePhoneGetNumberActivity},
			{Name: goPayAppChangePhoneStartActivityName, Definition: s.GoPayAppChangePhoneStartActivity},
			{Name: goPayAppChangePhoneRetryActivityName, Definition: s.GoPayAppChangePhoneRetryActivity},
			{Name: goPayAppSMSCancelBeforeRotationActivityName, Definition: s.GoPayAppSMSCancelBeforeRotationActivity},
			{Name: goPayAppSMSFinishActivityName, Definition: s.GoPayAppSMSFinishActivity},
			{Name: goPayAppSMSRequestAdditionalCodeActivityName, Definition: s.GoPayAppSMSRequestAdditionalCodeActivity},
			{Name: goPayAppChangePhoneCompleteActivityName, Definition: s.GoPayAppChangePhoneCompleteActivity},
			{Name: goPayAppDeactivateStartActivityName, Definition: s.GoPayAppDeactivateStartActivity},
			{Name: goPayAppDeactivateCompleteActivityName, Definition: s.GoPayAppDeactivateCompleteActivity},
			{Name: probePlusTrialActivityName, Definition: s.ProbePlusTrialAtomicActivity},
			{Name: probeTierActivityName, Definition: s.ProbeTierAtomicActivity},
			{Name: persistRegisteredActivityName, Definition: s.PersistRegisteredActivity},
			{Name: persistActivatedActivityName, Definition: s.PersistActivatedActivity},
			{Name: markJobFailedActivityName, Definition: s.MarkJobFailedActivity},
			{Name: markJobSucceededActivityName, Definition: s.MarkJobSucceededActivity},
		},
	}
}
