package gptplugin

const (
	StepProtocolUseProxy             = "protocol_use_proxy"
	StepDynamicIPCreateSession       = "dynamic_ip_create_session"
	StepDynamicIPExitGeo             = "dynamic_ip_exit_geo"
	StepDynamicIPPreflight           = "dynamic_ip_preflight"
	StepEnsureLogon                  = "ensure_logon"
	StepProbePlusTrial               = "probe_plus_trial"
	StepProbeTier                    = "probe_tier"
	StepLoginSession                 = "login_session"
	StepLoginSessionStart            = "login_session_start"
	StepLoginSessionBrowser          = "login_session_browser"
	StepLoginSessionProtocol         = "login_session_protocol"
	StepLoginSessionProtocolStart    = "login_session_protocol_start"
	StepLoginSessionProtocolOTPWait  = "login_session_protocol_otp_wait"
	StepLoginSessionProtocolComplete = "login_session_protocol_complete"
	StepLoginSessionOTPRequest       = "login_session_otp_request"
	StepLoginSessionOTPWait          = "login_session_otp_wait"
	StepLoginSessionComplete         = "login_session_complete"
	StepCodexOAuthAcquirePhone       = "codex_oauth_acquire_phone"
	StepCodexOAuthProtocolStart      = "codex_oauth_protocol_start"
	StepCodexOAuthProtocolDetect     = "codex_oauth_protocol_detect"
	StepCodexOAuthProtocolEmail      = "codex_oauth_protocol_email"
	StepCodexOAuthProtocolPassword   = "codex_oauth_protocol_password"
	StepCodexOAuthProtocolEmailOTP   = "codex_oauth_protocol_email_otp"
	StepCodexOAuthProtocolAddPhone   = "codex_oauth_protocol_add_phone"
	StepCodexOAuthProtocolComplete   = "codex_oauth_protocol_complete"
	StepCodexOAuthBrowserStart       = "codex_oauth_browser_start"
	StepCodexOAuthBrowserDetect      = "codex_oauth_browser_detect"
	StepCodexOAuthBrowserEmail       = "codex_oauth_browser_email"
	StepCodexOAuthBrowserPassword    = "codex_oauth_browser_password"
	StepCodexOAuthBrowserEmailOTP    = "codex_oauth_browser_email_otp"
	StepCodexOAuthBrowserAddPhone    = "codex_oauth_browser_add_phone"
	StepCodexOAuthBrowserComplete    = "codex_oauth_browser_complete"
	StepCodexOAuthReleasePhone       = "codex_oauth_release_phone"
)
