syntax = "proto3";

package orchestrator;

option go_package = "./;pb";

service OTPService {
  rpc SubmitOTP(SubmitOTPRequest) returns (SubmitOTPResponse);
  rpc ResendOTP(ResendOTPRequest) returns (ResendOTPResponse);
}

message SubmitOTPRequest {
  reserved 1, 2;
  reserved "job_id", "account_id";
  string otp = 3;
  string channel = 4;
  string target = 5;
}

message SubmitOTPResponse {
  bool success = 1;
  string job_id = 2;
  string error_message = 3;
}

message ResendOTPRequest {
  string job_id = 1;
  reserved 2, 3;
  reserved "account_id", "kind";
}

message ResendOTPResponse {
  bool success = 1;
  string job_id = 2;
  string error_message = 3;
}
